name: Deploy to Production

on:
  push:
    branches:
      - karthik

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd ~/asrivo-website/asrivo-website
            git pull origin karthik
            sudo docker stop asrivo-website || true
            sudo docker rm asrivo-website || true
            sudo docker build --no-cache -t asrivo-website:latest .
            sudo docker run -d --name asrivo-website -p 3000:3000 \
              --env-file ~/.env.production \
              asrivo-website:latest